/*****************************************************************************
*
* Copyright (c) 2000 - 2013, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

// ************************************************************************* //
//  File: avtShrinkPlotFilter.C
// ************************************************************************* //

#include <avtShrinkPlotFilter.h>
#include <vtkUnstructuredGrid.h>
#include <vtkPointData.h>
#include <vtkPoints.h>
#include <vtkCell.h>
#include<DebugStream.h>


// ****************************************************************************
//  Method: avtShrinkPlotFilter constructor
//
//  Programmer: guillaume -- generated by xml2avt
//  Creation:   Tue Nov 26 17:53:13 PST 2013
//
// ****************************************************************************

avtShrinkPlotFilter::avtShrinkPlotFilter()
{
    _scale = 0.5;
}


// ****************************************************************************
//  Method: avtShrinkPlotFilter destructor
//
//  Programmer: guillaume -- generated by xml2avt
//  Creation:   Tue Nov 26 17:53:13 PST 2013
//
//  Modifications:
//
// ****************************************************************************

avtShrinkPlotFilter::~avtShrinkPlotFilter()
{
}


// ****************************************************************************
//  Method:  avtShrinkPlotFilter::Create
//
//  Programmer: guillaume -- generated by xml2avt
//  Creation:   Tue Nov 26 17:53:13 PST 2013
//
// ****************************************************************************

avtFilter *
avtShrinkPlotFilter::Create()
{
    return new avtShrinkPlotFilter();
}


// ****************************************************************************
//  Method:      avtShrinkPlotFilter::SetAtts
//
//  Purpose:
//      Sets the state of the filter based on the attribute object.
//
//  Arguments:
//      a        The attributes to use.
//
//  Programmer: guillaume -- generated by xml2avt
//  Creation:   Tue Nov 26 17:53:13 PST 2013
//
// ****************************************************************************

void
avtShrinkPlotFilter::SetAtts(const AttributeGroup *a)
{
    atts = *(const ScaleVal*)a;
}


// ****************************************************************************
//  Method: avtShrinkPlotFilter::Equivalent
//
//  Purpose:
//      Returns true if creating a new avtShrinkPlotFilter with the given
//      parameters would result in an equivalent avtShrinkPlotFilter.
//
//  Programmer: guillaume -- generated by xml2avt
//  Creation:   Tue Nov 26 17:53:13 PST 2013
//
// ****************************************************************************

bool
avtShrinkPlotFilter::Equivalent(const AttributeGroup *a)
{
    return (atts == *(ScaleVal*)a);
}


// ****************************************************************************
//  Method: avtShrinkPlotFilter::ExecuteData
//
//  Purpose:
//      Sends the specified input and output through the ShrinkPlot filter.
//
//  Arguments:
//      in_ds      The input dataset.
//      <unused>   The domain number.
//      <unused>   The label.
//
//  Returns:       The output dataset.
//
//  Programmer: guillaume -- generated by xml2avt
//  Creation:   Tue Nov 26 17:53:13 PST 2013
//
// ****************************************************************************

vtkDataSet *
avtShrinkPlotFilter::ExecuteData(vtkDataSet *input, int nbArgs, std::string args)
{
    //Get the scale value
    _scale = atts.GetScal();
    if(_scale < 0.) _scale = 0.;
    if(_scale > 1.) _scale = 1.;

    //Creating the output grid
    vtkUnstructuredGrid * output = vtkUnstructuredGrid::New();

    //Get the number of cells and creating the array that will contains the new points of the cells
    vtkIdType nbCells = input->GetNumberOfCells();
    vtkPoints * points = vtkPoints::New();

    //For every cells..
    for(int i=0; i<nbCells; i++)
    {
        //We recover the cell's points coordonates
        vtkCell * triangle = input->GetCell(i);
        double * a = new double[3];
        input->GetPoint(triangle->GetPointId(0), a);
        double * b = new double[3];
        input->GetPoint(triangle->GetPointId(1), b);
        double * c = new double[3];
        input->GetPoint(triangle->GetPointId(2), c);

        //Then we compute the centroid of the triangle
        double * centroid = new double[3];
        this->Centroid(a,b,c,centroid);

        //After that we compute the new points coordonates
        double * temp = new double[3];
        this->Interpolate(a, centroid, temp);
        points->InsertNextPoint(temp);

        temp = new double[3];
        this->Interpolate(b, centroid, temp);
        points->InsertNextPoint(temp);

        temp = new double[3];
        this->Interpolate(c, centroid, temp);
        points->InsertNextPoint(temp);

        //We had the ids in the cell...
        vtkIdList * ids = vtkIdList::New();
        ids->SetNumberOfIds(3);
        ids->SetId(0, (i*3));
        ids->SetId(1, (i*3) + 1);
        ids->SetId(2, (i*3) + 2);

        //...that we place in the output grid
        output->InsertNextCell(VTK_TRIANGLE, ids);
    }

    //We finally place all the new points in the grid
    output->SetPoints(points);

    return output;
}


//Centroid calculation
void avtShrinkPlotFilter::Centroid(double * A, double * B, double * C, double * centroid)
{
    centroid[0] = (A[0] + B[0] + C[0]) / 3;
    centroid[1] = (A[1] + B[1] + C[1]) / 3;
    centroid[2] = (A[2] + B[2] + C[2]) / 3;
}


//Calculation of the new A point's coordonates in C thanks to the centroid B and the scale value
void avtShrinkPlotFilter::Interpolate(double * A, double * B, double * C)
{
    C[0] = _scale * B[0] - _scale * A[0] + A[0];
    C[1] = _scale * B[1] - _scale * A[1] + A[1];
    C[2] = _scale * B[2] - _scale * A[2] + A[2];
}
