/*****************************************************************************
*
* Copyright (c) 2000 - 2012, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

// ************************************************************************* //
//  File: avtShrinkPlotFilter.C
// ************************************************************************* //

#include <avtShrinkPlotFilter.h>
#include <vtkUnstructuredGrid.h>


// ****************************************************************************
//  Method: avtShrinkPlotFilter constructor
//
//  Programmer: grazimba -- generated by xml2avt
//  Creation:   Tue Nov 26 11:26:27 PDT 2013
//
// ****************************************************************************

avtShrinkPlotFilter::avtShrinkPlotFilter()
{
}


// ****************************************************************************
//  Method: avtShrinkPlotFilter destructor
//
//  Programmer: grazimba -- generated by xml2avt
//  Creation:   Tue Nov 26 11:26:27 PDT 2013
//
//  Modifications:
//
// ****************************************************************************

avtShrinkPlotFilter::~avtShrinkPlotFilter()
{
}


// ****************************************************************************
//  Method:  avtShrinkPlotFilter::Create
//
//  Programmer: grazimba -- generated by xml2avt
//  Creation:   Tue Nov 26 11:26:27 PDT 2013
//
// ****************************************************************************

avtFilter *
avtShrinkPlotFilter::Create()
{
    return new avtShrinkPlotFilter();
}


// ****************************************************************************
//  Method:      avtShrinkPlotFilter::SetAtts
//
//  Purpose:
//      Sets the state of the filter based on the attribute object.
//
//  Arguments:
//      a        The attributes to use.
//
//  Programmer: grazimba -- generated by xml2avt
//  Creation:   Tue Nov 26 11:26:27 PDT 2013
//
// ****************************************************************************

void
avtShrinkPlotFilter::SetAtts(const AttributeGroup *a)
{
    atts = *(const ScaleVal*)a;
}


// ****************************************************************************
//  Method: avtShrinkPlotFilter::Equivalent
//
//  Purpose:
//      Returns true if creating a new avtShrinkPlotFilter with the given
//      parameters would result in an equivalent avtShrinkPlotFilter.
//
//  Programmer: grazimba -- generated by xml2avt
//  Creation:   Tue Nov 26 11:26:27 PDT 2013
//
// ****************************************************************************

bool
avtShrinkPlotFilter::Equivalent(const AttributeGroup *a)
{
    return (atts == *(ScaleVal*)a);
}


// ****************************************************************************
//  Method: avtShrinkPlotFilter::ExecuteData
//
//  Purpose:
//      Sends the specified input and output through the ShrinkPlot filter.
//
//  Arguments:
//      in_ds      The input dataset.
//      <unused>   The domain number.
//      <unused>   The label.
//
//  Returns:       The output dataset.
//
//  Programmer: grazimba -- generated by xml2avt
//  Creation:   Tue Nov 26 11:26:27 PDT 2013
//
// ****************************************************************************

vtkDataSet *
avtShrinkPlotFilter::ExecuteData(vtkDataSet *input, int, std::string)
{
    vtkUnstructuredGrid * output = vtkUnstructuredGrid::New();
    return output;
}

void avtShrinkPlotFilter::Centroid(double * A, double * B, double * C, double * barycentre)
{
    barycentre[0] = (A[0] + B[0] + C[0]) / 3;
    barycentre[1] = (A[1] + B[1] + C[1]) / 3;
    barycentre[2] = (A[2] + B[2] + C[2]) / 3;
}

void avtShrinkPlotFilter::Interpolate(double * A, double * B, double * C)
{
    C[0] = _scale * B[0] - _scale * A[0] + A[0];
    C[1] = _scale * B[1] - _scale * A[1] + A[1];
    C[2] = _scale * B[2] - _scale * A[2] + A[2];
}
