/*****************************************************************************
*
* Copyright (c) 2000 - 2012, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

#include <PyScaleVal.h>
#include <ObserverToCallback.h>
#include <stdio.h>
#include <snprintf.h>

// ****************************************************************************
// Module: PyScaleVal
//
// Purpose: 
//   Contains the scale value for the shrink
//
// Note:       Autogenerated by xml2python. Do not modify by hand!
//
// Programmer: xml2python
// Creation:   omitted
//
// ****************************************************************************

//
// This struct contains the Python type information and a ScaleVal.
//
struct ScaleValObject
{
    PyObject_HEAD
    ScaleVal *data;
    bool        owns;
    PyObject   *parent;
};

//
// Internal prototypes
//
static PyObject *NewScaleVal(int);

std::string
PyScaleVal_ToString(const ScaleVal *atts, const char *prefix)
{
    std::string str; 
    char tmpStr[1000]; 

    SNPRINTF(tmpStr, 1000, "%sScale = %g\n", prefix, atts->GetScale());
    str += tmpStr;
    return str;
}

static PyObject *
ScaleVal_Notify(PyObject *self, PyObject *args)
{
    ScaleValObject *obj = (ScaleValObject *)self;
    obj->data->Notify();
    Py_INCREF(Py_None);
    return Py_None;
}

/*static*/ PyObject *
ScaleVal_SetScale(PyObject *self, PyObject *args)
{
    ScaleValObject *obj = (ScaleValObject *)self;

    float fval;
    if(!PyArg_ParseTuple(args, "f", &fval))
        return NULL;

    // Set the Scale in the object.
    obj->data->SetScale(fval);

    Py_INCREF(Py_None);
    return Py_None;
}

/*static*/ PyObject *
ScaleVal_GetScale(PyObject *self, PyObject *args)
{
    ScaleValObject *obj = (ScaleValObject *)self;
    PyObject *retval = PyFloat_FromDouble(double(obj->data->GetScale()));
    return retval;
}



PyMethodDef PyScaleVal_methods[SCALEVAL_NMETH] = {
    {"Notify", ScaleVal_Notify, METH_VARARGS},
    {"SetScale", ScaleVal_SetScale, METH_VARARGS},
    {"GetScale", ScaleVal_GetScale, METH_VARARGS},
    {NULL, NULL}
};

//
// Type functions
//

static void
ScaleVal_dealloc(PyObject *v)
{
   ScaleValObject *obj = (ScaleValObject *)v;
   if(obj->parent != 0)
       Py_DECREF(obj->parent);
   if(obj->owns)
       delete obj->data;
}

static int
ScaleVal_compare(PyObject *v, PyObject *w)
{
    ScaleVal *a = ((ScaleValObject *)v)->data;
    ScaleVal *b = ((ScaleValObject *)w)->data;
    return (*a == *b) ? 0 : -1;
}

PyObject *
PyScaleVal_getattr(PyObject *self, char *name)
{
    if(strcmp(name, "Scale") == 0)
        return ScaleVal_GetScale(self, NULL);

    return Py_FindMethod(PyScaleVal_methods, self, name);
}

int
PyScaleVal_setattr(PyObject *self, char *name, PyObject *args)
{
    // Create a tuple to contain the arguments since all of the Set
    // functions expect a tuple.
    PyObject *tuple = PyTuple_New(1);
    PyTuple_SET_ITEM(tuple, 0, args);
    Py_INCREF(args);
    PyObject *obj = NULL;

    if(strcmp(name, "Scale") == 0)
        obj = ScaleVal_SetScale(self, tuple);

    if(obj != NULL)
        Py_DECREF(obj);

    Py_DECREF(tuple);
    if( obj == NULL)
        PyErr_Format(PyExc_RuntimeError, "Unable to set unknown attribute: '%s'", name);
    return (obj != NULL) ? 0 : -1;
}

static int
ScaleVal_print(PyObject *v, FILE *fp, int flags)
{
    ScaleValObject *obj = (ScaleValObject *)v;
    fprintf(fp, "%s", PyScaleVal_ToString(obj->data, "").c_str());
    return 0;
}

PyObject *
ScaleVal_str(PyObject *v)
{
    ScaleValObject *obj = (ScaleValObject *)v;
    return PyString_FromString(PyScaleVal_ToString(obj->data,"").c_str());
}

//
// The doc string for the class.
//
#if PY_MAJOR_VERSION > 2 || (PY_MAJOR_VERSION == 2 && PY_MINOR_VERSION >= 5)
static const char *ScaleVal_Purpose = "Contains the scale value for the shrink";
#else
static char *ScaleVal_Purpose = "Contains the scale value for the shrink";
#endif

//
// The type description structure
//
static PyTypeObject ScaleValType =
{
    //
    // Type header
    //
    PyObject_HEAD_INIT(&PyType_Type)
    0,                                   // ob_size
    "ScaleVal",                    // tp_name
    sizeof(ScaleValObject),        // tp_basicsize
    0,                                   // tp_itemsize
    //
    // Standard methods
    //
    (destructor)ScaleVal_dealloc,  // tp_dealloc
    (printfunc)ScaleVal_print,     // tp_print
    (getattrfunc)PyScaleVal_getattr, // tp_getattr
    (setattrfunc)PyScaleVal_setattr, // tp_setattr
    (cmpfunc)ScaleVal_compare,     // tp_compare
    (reprfunc)0,                         // tp_repr
    //
    // Type categories
    //
    0,                                   // tp_as_number
    0,                                   // tp_as_sequence
    0,                                   // tp_as_mapping
    //
    // More methods
    //
    0,                                   // tp_hash
    0,                                   // tp_call
    (reprfunc)ScaleVal_str,        // tp_str
    0,                                   // tp_getattro
    0,                                   // tp_setattro
    0,                                   // tp_as_buffer
    Py_TPFLAGS_CHECKTYPES,               // tp_flags
    ScaleVal_Purpose,              // tp_doc
    0,                                   // tp_traverse
    0,                                   // tp_clear
    0,                                   // tp_richcompare
    0                                    // tp_weaklistoffset
};

//
// Helper functions for object allocation.
//

static ScaleVal *defaultAtts = 0;
static ScaleVal *currentAtts = 0;

static PyObject *
NewScaleVal(int useCurrent)
{
    ScaleValObject *newObject;
    newObject = PyObject_NEW(ScaleValObject, &ScaleValType);
    if(newObject == NULL)
        return NULL;
    if(useCurrent && currentAtts != 0)
        newObject->data = new ScaleVal(*currentAtts);
    else if(defaultAtts != 0)
        newObject->data = new ScaleVal(*defaultAtts);
    else
        newObject->data = new ScaleVal;
    newObject->owns = true;
    newObject->parent = 0;
    return (PyObject *)newObject;
}

static PyObject *
WrapScaleVal(const ScaleVal *attr)
{
    ScaleValObject *newObject;
    newObject = PyObject_NEW(ScaleValObject, &ScaleValType);
    if(newObject == NULL)
        return NULL;
    newObject->data = (ScaleVal *)attr;
    newObject->owns = false;
    newObject->parent = 0;
    return (PyObject *)newObject;
}

///////////////////////////////////////////////////////////////////////////////
//
// Interface that is exposed to the VisIt module.
//
///////////////////////////////////////////////////////////////////////////////

PyObject *
ScaleVal_new(PyObject *self, PyObject *args)
{
    int useCurrent = 0;
    if (!PyArg_ParseTuple(args, "i", &useCurrent))
    {
        if (!PyArg_ParseTuple(args, ""))
            return NULL;
        else
            PyErr_Clear();
    }

    return (PyObject *)NewScaleVal(useCurrent);
}

//
// Plugin method table. These methods are added to the visitmodule's methods.
//
static PyMethodDef ScaleValMethods[] = {
    {"ScaleVal", ScaleVal_new, METH_VARARGS},
    {NULL,      NULL}        /* Sentinel */
};

static Observer *ScaleValObserver = 0;

std::string
PyScaleVal_GetLogString()
{
    std::string s("ScaleVal = ScaleVal()\n");
    if(currentAtts != 0)
        s += PyScaleVal_ToString(currentAtts, "ScaleVal.");
    return s;
}

static void
PyScaleVal_CallLogRoutine(Subject *subj, void *data)
{
    ScaleVal *atts = (ScaleVal *)subj;
    typedef void (*logCallback)(const std::string &);
    logCallback cb = (logCallback)data;

    if(cb != 0)
    {
        std::string s("ScaleVal = ScaleVal()\n");
        s += PyScaleVal_ToString(currentAtts, "ScaleVal.");
        cb(s);
    }
}

void
PyScaleVal_StartUp(ScaleVal *subj, void *data)
{
    if(subj == 0)
        return;

    currentAtts = subj;
    PyScaleVal_SetDefaults(subj);

    //
    // Create the observer that will be notified when the attributes change.
    //
    if(ScaleValObserver == 0)
    {
        ScaleValObserver = new ObserverToCallback(subj,
            PyScaleVal_CallLogRoutine, (void *)data);
    }

}

void
PyScaleVal_CloseDown()
{
    delete defaultAtts;
    defaultAtts = 0;
    delete ScaleValObserver;
    ScaleValObserver = 0;
}

PyMethodDef *
PyScaleVal_GetMethodTable(int *nMethods)
{
    *nMethods = 1;
    return ScaleValMethods;
}

bool
PyScaleVal_Check(PyObject *obj)
{
    return (obj->ob_type == &ScaleValType);
}

ScaleVal *
PyScaleVal_FromPyObject(PyObject *obj)
{
    ScaleValObject *obj2 = (ScaleValObject *)obj;
    return obj2->data;
}

PyObject *
PyScaleVal_New()
{
    return NewScaleVal(0);
}

PyObject *
PyScaleVal_Wrap(const ScaleVal *attr)
{
    return WrapScaleVal(attr);
}

void
PyScaleVal_SetParent(PyObject *obj, PyObject *parent)
{
    ScaleValObject *obj2 = (ScaleValObject *)obj;
    obj2->parent = parent;
}

void
PyScaleVal_SetDefaults(const ScaleVal *atts)
{
    if(defaultAtts)
        delete defaultAtts;

    defaultAtts = new ScaleVal(*atts);
}

