/*****************************************************************************
*
* Copyright (c) 2000 - 2013, Lawrence Livermore National Security, LLC
* Produced at the Lawrence Livermore National Laboratory
* LLNL-CODE-442911
* All rights reserved.
*
* This file is  part of VisIt. For  details, see https://visit.llnl.gov/.  The
* full copyright notice is contained in the file COPYRIGHT located at the root
* of the VisIt distribution or at http://www.llnl.gov/visit/copyright.html.
*
* Redistribution  and  use  in  source  and  binary  forms,  with  or  without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of  source code must  retain the above  copyright notice,
*    this list of conditions and the disclaimer below.
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this  list of  conditions  and  the  disclaimer (as noted below)  in  the
*    documentation and/or other materials provided with the distribution.
*  - Neither the name of  the LLNS/LLNL nor the names of  its contributors may
*    be used to endorse or promote products derived from this software without
*    specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT  HOLDERS AND CONTRIBUTORS "AS IS"
* AND ANY EXPRESS OR  IMPLIED WARRANTIES, INCLUDING,  BUT NOT  LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND  FITNESS FOR A PARTICULAR  PURPOSE
* ARE  DISCLAIMED. IN  NO EVENT  SHALL LAWRENCE  LIVERMORE NATIONAL  SECURITY,
* LLC, THE  U.S.  DEPARTMENT OF  ENERGY  OR  CONTRIBUTORS BE  LIABLE  FOR  ANY
* DIRECT,  INDIRECT,   INCIDENTAL,   SPECIAL,   EXEMPLARY,  OR   CONSEQUENTIAL
* DAMAGES (INCLUDING, BUT NOT  LIMITED TO, PROCUREMENT OF  SUBSTITUTE GOODS OR
* SERVICES; LOSS OF  USE, DATA, OR PROFITS; OR  BUSINESS INTERRUPTION) HOWEVER
* CAUSED  AND  ON  ANY  THEORY  OF  LIABILITY,  WHETHER  IN  CONTRACT,  STRICT
* LIABILITY, OR TORT  (INCLUDING NEGLIGENCE OR OTHERWISE)  ARISING IN ANY  WAY
* OUT OF THE  USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
* DAMAGE.
*
*****************************************************************************/

#include <ScaleVal.h>
#include <DataNode.h>

// ****************************************************************************
// Method: ScaleVal::ScaleVal
//
// Purpose: 
//   Init utility for the ScaleVal class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void ScaleVal::Init()
{

    ScaleVal::SelectAll();
}

// ****************************************************************************
// Method: ScaleVal::ScaleVal
//
// Purpose: 
//   Copy utility for the ScaleVal class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void ScaleVal::Copy(const ScaleVal &obj)
{
    Scal = obj.Scal;

    ScaleVal::SelectAll();
}

// Type map format string
const char *ScaleVal::TypeMapFormatString = SCALEVAL_TMFS;
const AttributeGroup::private_tmfs_t ScaleVal::TmfsStruct = {SCALEVAL_TMFS};


// ****************************************************************************
// Method: ScaleVal::ScaleVal
//
// Purpose: 
//   Default constructor for the ScaleVal class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

ScaleVal::ScaleVal() : 
    AttributeSubject(ScaleVal::TypeMapFormatString)
{
    ScaleVal::Init();
}

// ****************************************************************************
// Method: ScaleVal::ScaleVal
//
// Purpose: 
//   Constructor for the derived classes of ScaleVal class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

ScaleVal::ScaleVal(private_tmfs_t tmfs) : 
    AttributeSubject(tmfs.tmfs)
{
    ScaleVal::Init();
}

// ****************************************************************************
// Method: ScaleVal::ScaleVal
//
// Purpose: 
//   Copy constructor for the ScaleVal class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

ScaleVal::ScaleVal(const ScaleVal &obj) : 
    AttributeSubject(ScaleVal::TypeMapFormatString)
{
    ScaleVal::Copy(obj);
}

// ****************************************************************************
// Method: ScaleVal::ScaleVal
//
// Purpose: 
//   Copy constructor for derived classes of the ScaleVal class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

ScaleVal::ScaleVal(const ScaleVal &obj, private_tmfs_t tmfs) : 
    AttributeSubject(tmfs.tmfs)
{
    ScaleVal::Copy(obj);
}

// ****************************************************************************
// Method: ScaleVal::~ScaleVal
//
// Purpose: 
//   Destructor for the ScaleVal class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

ScaleVal::~ScaleVal()
{
    // nothing here
}

// ****************************************************************************
// Method: ScaleVal::operator = 
//
// Purpose: 
//   Assignment operator for the ScaleVal class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

ScaleVal& 
ScaleVal::operator = (const ScaleVal &obj)
{
    if (this == &obj) return *this;

    ScaleVal::Copy(obj);

    return *this;
}

// ****************************************************************************
// Method: ScaleVal::operator == 
//
// Purpose: 
//   Comparison operator == for the ScaleVal class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
ScaleVal::operator == (const ScaleVal &obj) const
{
    // Create the return value
    return ((Scal == obj.Scal));
}

// ****************************************************************************
// Method: ScaleVal::operator != 
//
// Purpose: 
//   Comparison operator != for the ScaleVal class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
ScaleVal::operator != (const ScaleVal &obj) const
{
    return !(this->operator == (obj));
}

// ****************************************************************************
// Method: ScaleVal::TypeName
//
// Purpose: 
//   Type name method for the ScaleVal class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

const std::string
ScaleVal::TypeName() const
{
    return "ScaleVal";
}

// ****************************************************************************
// Method: ScaleVal::CopyAttributes
//
// Purpose: 
//   CopyAttributes method for the ScaleVal class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
ScaleVal::CopyAttributes(const AttributeGroup *atts)
{
    if(TypeName() != atts->TypeName())
        return false;

    // Call assignment operator.
    const ScaleVal *tmp = (const ScaleVal *)atts;
    *this = *tmp;

    return true;
}

// ****************************************************************************
// Method: ScaleVal::CreateCompatible
//
// Purpose: 
//   CreateCompatible method for the ScaleVal class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

AttributeSubject *
ScaleVal::CreateCompatible(const std::string &tname) const
{
    AttributeSubject *retval = 0;
    if(TypeName() == tname)
        retval = new ScaleVal(*this);
    // Other cases could go here too. 

    return retval;
}

// ****************************************************************************
// Method: ScaleVal::NewInstance
//
// Purpose: 
//   NewInstance method for the ScaleVal class.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

AttributeSubject *
ScaleVal::NewInstance(bool copy) const
{
    AttributeSubject *retval = 0;
    if(copy)
        retval = new ScaleVal(*this);
    else
        retval = new ScaleVal;

    return retval;
}

// ****************************************************************************
// Method: ScaleVal::SelectAll
//
// Purpose: 
//   Selects all attributes.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
ScaleVal::SelectAll()
{
    Select(ID_Scal, (void *)&Scal);
}

///////////////////////////////////////////////////////////////////////////////
// Persistence methods
///////////////////////////////////////////////////////////////////////////////

// ****************************************************************************
// Method: ScaleVal::CreateNode
//
// Purpose: 
//   This method creates a DataNode representation of the object so it can be saved to a config file.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
ScaleVal::CreateNode(DataNode *parentNode, bool completeSave, bool forceAdd)
{
    if(parentNode == 0)
        return false;

    ScaleVal defaultObject;
    bool addToParent = false;
    // Create a node for ScaleVal.
    DataNode *node = new DataNode("ScaleVal");

    if(completeSave || !FieldsEqual(ID_Scal, &defaultObject))
    {
        addToParent = true;
        node->AddNode(new DataNode("Scal", Scal));
    }


    // Add the node to the parent node.
    if(addToParent || forceAdd)
        parentNode->AddNode(node);
    else
        delete node;

    return (addToParent || forceAdd);
}

// ****************************************************************************
// Method: ScaleVal::SetFromNode
//
// Purpose: 
//   This method sets attributes in this object from values in a DataNode representation of the object.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

void
ScaleVal::SetFromNode(DataNode *parentNode)
{
    if(parentNode == 0)
        return;

    DataNode *searchNode = parentNode->GetNode("ScaleVal");
    if(searchNode == 0)
        return;

    DataNode *node;
    if((node = searchNode->GetNode("Scal")) != 0)
        SetScal(node->AsFloat());
}

///////////////////////////////////////////////////////////////////////////////
// Set property methods
///////////////////////////////////////////////////////////////////////////////

void
ScaleVal::SetScal(float Scal_)
{
    Scal = Scal_;
    Select(ID_Scal, (void *)&Scal);
}

///////////////////////////////////////////////////////////////////////////////
// Get property methods
///////////////////////////////////////////////////////////////////////////////

float
ScaleVal::GetScal() const
{
    return Scal;
}

///////////////////////////////////////////////////////////////////////////////
// Keyframing methods
///////////////////////////////////////////////////////////////////////////////

// ****************************************************************************
// Method: ScaleVal::GetFieldName
//
// Purpose: 
//   This method returns the name of a field given its index.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

std::string
ScaleVal::GetFieldName(int index) const
{
    switch (index)
    {
    case ID_Scal: return "Scal";
    default:  return "invalid index";
    }
}

// ****************************************************************************
// Method: ScaleVal::GetFieldType
//
// Purpose: 
//   This method returns the type of a field given its index.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

AttributeGroup::FieldType
ScaleVal::GetFieldType(int index) const
{
    switch (index)
    {
    case ID_Scal: return FieldType_float;
    default:  return FieldType_unknown;
    }
}

// ****************************************************************************
// Method: ScaleVal::GetFieldTypeName
//
// Purpose: 
//   This method returns the name of a field type given its index.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

std::string
ScaleVal::GetFieldTypeName(int index) const
{
    switch (index)
    {
    case ID_Scal: return "float";
    default:  return "invalid index";
    }
}

// ****************************************************************************
// Method: ScaleVal::FieldsEqual
//
// Purpose: 
//   This method compares two fields and return true if they are equal.
//
// Note:       Autogenerated by xml2atts.
//
// Programmer: xml2atts
// Creation:   omitted
//
// Modifications:
//   
// ****************************************************************************

bool
ScaleVal::FieldsEqual(int index_, const AttributeGroup *rhs) const
{
    const ScaleVal &obj = *((const ScaleVal*)rhs);
    bool retval = false;
    switch (index_)
    {
    case ID_Scal:
        {  // new scope
        retval = (Scal == obj.Scal);
        }
        break;
    default: retval = false;
    }

    return retval;
}

///////////////////////////////////////////////////////////////////////////////
// User-defined methods.
///////////////////////////////////////////////////////////////////////////////

